name: Build Heavy Compile Test

on:
  workflow_dispatch:

jobs:
  build-heavy-compile:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: hendrikmuhs/ccache-action@15457da8f7bbf9b2c71f2efebd847c1a84650208

    - name: Configure build
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build with timing
      run: |
        cd build
        ninja

    - name: Show ccache statistics
      run: ccache --show-stats